# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/SimWang/Documents/CPE233/Final Project/tetris txt/RAT_MCU_v2/RAT_MCU.cache/wt} [current_project]
set_property parent.project_path {C:/Users/SimWang/Documents/CPE233/Final Project/tetris txt/RAT_MCU_v2/RAT_MCU.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo {c:/Users/SimWang/Documents/CPE233/Final Project/tetris txt/RAT_MCU_v2/RAT_MCU.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  {C:/Users/SimWang/Documents/CPE233/Final Project/tetris txt/RAT_MCU_v2/RAT_MCU.srcs/sources_1/imports/weise/Desktop/RAT4/RAT4.srcs/sources_1/new/ALU.vhd}
  {C:/Users/SimWang/Documents/CPE233/Final Project/tetris txt/RAT_MCU_v2/RAT_MCU.srcs/sources_1/new/ALU_MUX.vhd}
  {C:/Users/SimWang/Documents/CPE233/Final Project/tetris txt/RAT_MCU_v2/RAT_MCU.srcs/sources_1/imports/weise/Desktop/RAT5/RAT5.srcs/sources_1/new/ControlUnit.vhd}
  {C:/Users/SimWang/Documents/CPE233/Final Project/tetris txt/RAT_MCU_v2/RAT_MCU.srcs/sources_1/new/MCU.vhd}
  {C:/Users/SimWang/Documents/CPE233/Final Project/tetris txt/RAT_MCU_v2/RAT_MCU.srcs/sources_1/imports/weise/Desktop/rat_2/rat_2.srcs/sources_1/new/PC.vhd}
  {C:/Users/SimWang/Documents/CPE233/Final Project/tetris txt/RAT_MCU_v2/RAT_MCU.srcs/sources_1/imports/weise/Desktop/REG_FILE/REG_FILE.srcs/sources_1/new/REG_FILE.vhd}
  {C:/Users/SimWang/Documents/CPE233/Final Project/tetris txt/RAT_MCU_v2/RAT_MCU.srcs/sources_1/new/RNG.vhd}
  {C:/Users/SimWang/Documents/CPE233/Final Project/tetris txt/RAT_MCU_v2/RAT_MCU.srcs/sources_1/imports/Desktop/REG_FILE/REG_FILE.srcs/sources_1/new/Scratch_RAM.vhd}
  {C:/Users/SimWang/Documents/CPE233/Final Project/tetris txt/RAT_MCU_v2/RAT_MCU.srcs/sources_1/imports/Desktop/VGAdrive.vhd}
  {C:/Users/SimWang/Documents/CPE233/Final Project/tetris txt/RAT_MCU_v2/RAT_MCU.srcs/sources_1/new/cz_flags.vhd}
  {C:/Users/SimWang/Documents/CPE233/Final Project/tetris txt/RAT_MCU_v2/RAT_MCU.srcs/sources_1/new/int_f.vhd}
  {C:/Users/SimWang/Documents/CPE233/Final Project/tetris txt/RAT_MCU_v2/RAT_MCU.srcs/sources_1/imports/weise/Desktop/rat_2/rat_2.srcs/sources_1/new/pc_mux.vhd}
  {C:/Users/SimWang/Documents/CPE233/Final Project/tetris txt/RAT_MCU_v2/RAT_MCU.srcs/sources_1/imports/weise/Downloads/RatSim v0.61/RatSimulator/prog_rom.vhd}
  {C:/Users/SimWang/Documents/CPE233/Final Project/tetris txt/RAT_MCU_v2/RAT_MCU.srcs/sources_1/imports/weise/Desktop/rat_2/rat_2.srcs/sources_1/new/programCounter.vhd}
  {C:/Users/SimWang/Documents/CPE233/Final Project/tetris txt/RAT_MCU_v2/RAT_MCU.srcs/sources_1/imports/Desktop/ram2k_8.vhd}
  {C:/Users/SimWang/Documents/CPE233/Final Project/tetris txt/RAT_MCU_v2/RAT_MCU.srcs/sources_1/imports/weise/Desktop/CPE133/sseg.vhd}
  {C:/Users/SimWang/Documents/CPE233/Final Project/tetris txt/RAT_MCU_v2/RAT_MCU.srcs/sources_1/imports/Desktop/SP/SP.srcs/sources_1/new/stack_pointer.vhd}
  {C:/Users/SimWang/Documents/CPE233/Final Project/tetris txt/RAT_MCU_v2/RAT_MCU.srcs/sources_1/imports/Desktop/vgaDriverBuffer.vhd}
  {C:/Users/SimWang/Documents/CPE233/Final Project/tetris txt/RAT_MCU_v2/RAT_MCU.srcs/sources_1/imports/Desktop/vga_clk_div.vhd}
  {C:/Users/SimWang/Documents/CPE233/Final Project/tetris txt/RAT_MCU_v2/RAT_MCU.srcs/sources_1/imports/Desktop/RAT_Wrapper.vhd}
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/SimWang/Documents/CPE233/Final Project/tetris txt/RAT_MCU_v2/RAT_MCU.srcs/constrs_1/new/RAT_Constraints.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/SimWang/Documents/CPE233/Final Project/tetris txt/RAT_MCU_v2/RAT_MCU.srcs/constrs_1/new/RAT_Constraints.xdc}}]

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top RAT_wrapper -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef RAT_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file RAT_wrapper_utilization_synth.rpt -pb RAT_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
